/**
 * First-activation IndexNow submission list — a one-time, deliberate batch,
 * not an ongoing automatic mechanism (V1 has no automatic change detection;
 * see docs/indexnow.md... N/A — see the P3A/IndexNow audit report for the
 * full architecture discussion).
 *
 * Derived programmatically from the live production sitemap.xml (fetched
 * fresh, not from memory or earlier estimates), filtered to the classes the
 * user approved as the "principal PQNK knowledge corpus":
 *   - Homepage
 *   - Services, Validation, Founder, About
 *   - Science (index + all 10 domain pages)
 *   - Knowledge Papers (index + all 186 papers)
 *   - Crops (index + all 21 crops)
 *   - Machines (index + all 5 machines)
 * = 231 corpus URLs, plus one explicit one-time addition:
 *   - https://pedaver.com/sample-page/ — the legacy URL that now 301s to
 *     /founder/, included once so participating engines re-crawl it and
 *     pick up the redirect faster.
 * = 232 total.
 *
 * Explicitly excluded (utility pages / not the authoritative knowledge
 * corpus / still evolving): Resources, Advisory, Videos, Video Library,
 * Farmer Voices, Install, Contact.
 *
 * One correction made during derivation: 8 index-page URLs in sitemap.xml
 * (e.g. "https://pedaver.com/services") are listed WITHOUT a trailing
 * slash, even though every page's own canonical tag uses the trailing-slash
 * form and the no-slash form 301s to it (confirmed directly). This list uses
 * the canonical trailing-slash form throughout — submitting a URL that
 * itself immediately redirects again is not good IndexNow practice. The
 * sitemap itself was left unchanged, per instruction.
 */
export const FIRST_ACTIVATION_URLS: string[] = [
  "https://pedaver.com/",
  "https://pedaver.com/about/",
  "https://pedaver.com/founder/",
  "https://pedaver.com/services/",
  "https://pedaver.com/validation/",

  "https://pedaver.com/science/",
  "https://pedaver.com/science/soil/",
  "https://pedaver.com/science/plants/",
  "https://pedaver.com/science/water/",
  "https://pedaver.com/science/biodiversity/",
  "https://pedaver.com/science/nutrition/",
  "https://pedaver.com/science/crop-protection/",
  "https://pedaver.com/science/climate/",
  "https://pedaver.com/science/food-quality/",
  "https://pedaver.com/science/production-architecture/",
  "https://pedaver.com/science/transition/",

  "https://pedaver.com/crops/",
  "https://pedaver.com/crops/wheat/",
  "https://pedaver.com/crops/cotton/",
  "https://pedaver.com/crops/rice/",
  "https://pedaver.com/crops/citrus-kinnow/",
  "https://pedaver.com/crops/sugarcane/",
  "https://pedaver.com/crops/pomegranate/",
  "https://pedaver.com/crops/potato/",
  "https://pedaver.com/crops/mango/",
  "https://pedaver.com/crops/banana/",
  "https://pedaver.com/crops/olive/",
  "https://pedaver.com/crops/rose/",
  "https://pedaver.com/crops/chilli/",
  "https://pedaver.com/crops/onion-garlic/",
  "https://pedaver.com/crops/black-carrot/",
  "https://pedaver.com/crops/amla/",
  "https://pedaver.com/crops/bamboo/",
  "https://pedaver.com/crops/castor/",
  "https://pedaver.com/crops/watermelon/",
  "https://pedaver.com/crops/motha-grass/",
  "https://pedaver.com/crops/agroforestry/",
  "https://pedaver.com/crops/vegetables-oap/",

  "https://pedaver.com/machines/",
  "https://pedaver.com/machines/hardpan-breaker/",
  "https://pedaver.com/machines/raised-bed-shaper/",
  "https://pedaver.com/machines/sipp-planter/",
  "https://pedaver.com/machines/vipp-planter/",
  "https://pedaver.com/machines/mulcher-bed-renovator/",

  "https://pedaver.com/papers/",
  "https://pedaver.com/papers/the-evolution-of-seed-placement/",
  "https://pedaver.com/papers/transforming-wheat-production-through-pqnk/",
  "https://pedaver.com/papers/enhancing-wheat-crop-lifespan-through-pqnk/",
  "https://pedaver.com/papers/modern-semi-dwarf-wheat-vs-heirloom-and-ancient-varieties/",
  "https://pedaver.com/papers/transforming-pakistans-sugar-industry-through-pqnk/",
  "https://pedaver.com/papers/pqnk-paradigm-shift-for-climate-resilient-rice-cultivation/",
  "https://pedaver.com/papers/transforming-garlic-and-onion-cultivation-through-pqnk/",
  "https://pedaver.com/papers/restoring-prosperity-in-citrus-and-mango-orchards/",
  "https://pedaver.com/papers/optimizing-mango-pruning-within-a-pqnk-ecosystem/",
  "https://pedaver.com/papers/achieving-high-density-kinnow-plantation-through-pqnk/",
  "https://pedaver.com/papers/the-future-of-potato-cultivation-through-pqnk/",
  "https://pedaver.com/papers/watermelon-cultivation-under-pqnk/",
  "https://pedaver.com/papers/batoor-flower-management-in-mango-under-pqnk/",
  "https://pedaver.com/papers/commercial-rhodes-grass-production-under-pqnk/",
  "https://pedaver.com/papers/commercial-bamboo-plantation-under-pqnk/",
  "https://pedaver.com/papers/cotton-cultivation-by-mulching/",
  "https://pedaver.com/papers/fruit-tree-alleys-and-filler-crops-on-pqnk/",
  "https://pedaver.com/papers/achieving-high-density-pomegranate-production-through-pqnk/",
  "https://pedaver.com/papers/high-density-amla-farming-under-pqnk/",
  "https://pedaver.com/papers/pqnk-rose-production/",
  "https://pedaver.com/papers/high-anthocyanin-black-carrot-under-pqnk/",
  "https://pedaver.com/papers/citrus-flowering-and-fruiting-within-the-pqnk-ecosystem/",
  "https://pedaver.com/papers/tomato-cultivation-under-pqnk/",
  "https://pedaver.com/papers/strategic-pruning-of-brinjal-for-a-prolific-harvest/",
  "https://pedaver.com/papers/chilli-production-under-pqnk/",
  "https://pedaver.com/papers/banana-cultivation-on-pqnk/",
  "https://pedaver.com/papers/sugarcane-the-bamboo-principle/",
  "https://pedaver.com/papers/sugarcane-cultivation-on-pqnk/",
  "https://pedaver.com/papers/motha-grass-dominance-a-pqnk-interpretation/",
  "https://pedaver.com/papers/mitigating-post-harvest-losses-in-rice-through-pqnk/",
  "https://pedaver.com/papers/monitoring-soil-life-in-the-pqnk-system/",
  "https://pedaver.com/papers/managing-the-biological-transition/",
  "https://pedaver.com/papers/the-breathing-soil-humidity-and-soil-structure/",
  "https://pedaver.com/papers/unlocking-the-secrets-of-the-soil-deep-topsoil/",
  "https://pedaver.com/papers/the-mechanism-of-nutrient-absorption-in-pqnk-farming/",
  "https://pedaver.com/papers/why-is-oxygen-less-in-soil-air-why-is-co2-high/",
  "https://pedaver.com/papers/the-autonomous-biome-self-assembling-fungal-networks/",
  "https://pedaver.com/papers/the-healers-dialogue-from-weed-signal-to-soil-silence/",
  "https://pedaver.com/papers/deep-subsoil-remediation-and-activation/",
  "https://pedaver.com/papers/the-self-liberating-mineral-cycle/",
  "https://pedaver.com/papers/managing-soil-electrical-conductivity-and-redox-potential/",
  "https://pedaver.com/papers/the-qudratti-nizam-as-a-holistic-organism/",
  "https://pedaver.com/papers/soil-water-dynamics-microclimate-feedback-and-plant-vigor/",
  "https://pedaver.com/papers/the-pqnk-raised-bed-system-engineering-root-zones/",
  "https://pedaver.com/papers/the-management-of-soil-density/",
  "https://pedaver.com/papers/beyond-sand-silt-and-clay/",
  "https://pedaver.com/papers/role-of-soil-colloids-in-soil-properties/",
  "https://pedaver.com/papers/the-underground-air-water-air-balance-and-nitrogen-fixation/",
  "https://pedaver.com/papers/breaking-hardpan-without-machinery/",
  "https://pedaver.com/papers/the-weeds-as-soil-physicians/",
  "https://pedaver.com/papers/the-wholesale-four-step-system-to-end-water-scarcity/",
  "https://pedaver.com/papers/restoring-earths-hydrological-cycle-to-mitigate-erratic-weather/",
  "https://pedaver.com/papers/creating-on-farm-micro-water-cycles/",
  "https://pedaver.com/papers/smog-haze-and-the-unshakable-resilience-of-the-pqnk-farm/",
  "https://pedaver.com/papers/managing-saline-irrigation-water-and-soil-reclamation/",
  "https://pedaver.com/papers/the-silenced-clock-temperature-cued-plant-development/",
  "https://pedaver.com/papers/heatwaves-pollination-failure-and-the-pqnk-buffer/",
  "https://pedaver.com/papers/the-hydrological-transformation-of-agricultural-landscapes/",
  "https://pedaver.com/papers/evaluation-of-tube-well-water-quality-for-irrigation/",
  "https://pedaver.com/papers/can-high-tds-water-be-used-to-rehabilitate-saline-soils/",
  "https://pedaver.com/papers/channeling-plant-energy-managing-vegetative-growth/",
  "https://pedaver.com/papers/the-sacred-symbiosis-why-pqnk-feeds-plants/",
  "https://pedaver.com/papers/the-living-plant-a-primer-on-physiology-and-processes/",
  "https://pedaver.com/papers/above-soil-ecosystems-in-pqnk/",
  "https://pedaver.com/papers/the-paradox-of-resistance-pests-adapt-humans-degrade/",
  "https://pedaver.com/papers/understanding-nematode-damage-and-recovery-with-pqnk/",
  "https://pedaver.com/papers/cultivating-plant-intelligence-through-engineered-soil-gradients/",
  "https://pedaver.com/papers/the-plant-as-ceo-biological-agency-in-rhizobial-partnerships/",
  "https://pedaver.com/papers/what-this-uprooted-wheat-plant-is-telling-us/",
  "https://pedaver.com/papers/contour-line-farming-through-the-pqnk-lens/",
  "https://pedaver.com/papers/agroforestry-species-selection-under-the-pqnk-model/",
  "https://pedaver.com/papers/optimizing-tractor-setup-for-precision-planting/",
  "https://pedaver.com/papers/the-inherent-shelf-life-advantage-of-pqnk-produce/",
  "https://pedaver.com/papers/the-twofold-art-of-pruning-as-compensatory-grazing/",
  "https://pedaver.com/papers/the-philosophy-of-the-central-leader/",
  "https://pedaver.com/papers/the-pqnk-imperative-re-mothering-our-agriculture/",
  "https://pedaver.com/papers/rethinking-agricultural-systems-the-pqnk-framework/",
  "https://pedaver.com/papers/liberating-pakistans-economy-through-pqnk/",
  "https://pedaver.com/papers/the-foundational-primacy-of-agriculture-over-industry/",
  "https://pedaver.com/papers/the-global-cost-of-agricultural-degradation/",
  "https://pedaver.com/papers/the-perpetual-abundance-principle/",
  "https://pedaver.com/papers/the-universal-application-of-pqnk-from-soil-to-supper/",
  "https://pedaver.com/papers/quantifying-the-abundance/",
  "https://pedaver.com/papers/restoring-earths-operating-system/",
  "https://pedaver.com/papers/reviving-the-self-regulating-agroecosystem/",
  "https://pedaver.com/papers/embracing-pqnk-a-regenerative-paradigm/",
  "https://pedaver.com/papers/beyond-extraction-and-illusion/",
  "https://pedaver.com/papers/a-regenerative-imperative-a-pqnk-response/",
  "https://pedaver.com/papers/the-organismic-paradigm-quantum-reading-the-farm/",
  "https://pedaver.com/papers/the-bio-energetic-valuation-framework/",
  "https://pedaver.com/papers/the-economics-of-resilience-a-cost-benefit-analysis/",
  "https://pedaver.com/papers/the-autonomous-cycle-planting-and-harvesting/",
  "https://pedaver.com/papers/the-expression-of-genetic-blueprint-phytochemical-density/",
  "https://pedaver.com/papers/the-pqnk-framework-from-degenerative-to-sustainable/",
  "https://pedaver.com/papers/the-pqnk-perspective-on-micronutrients/",
  "https://pedaver.com/papers/the-role-of-supplemental-nutrition-in-pqnk/",
  "https://pedaver.com/papers/comparing-food-quality-pqnk-vs-aci/",
  "https://pedaver.com/papers/scientific-parameters-behind-shelf-life-and-pest-attraction/",
  "https://pedaver.com/papers/addressing-the-untrained-farm-workforce-gap-in-pakistan/",
  "https://pedaver.com/papers/pqnk-farming-in-practice-site-specific-solutions/",
  "https://pedaver.com/papers/advisory-for-one-acre-prosperity-in-vegetable-production/",
  "https://pedaver.com/papers/the-pqnk-validation-system/",
  "https://pedaver.com/papers/the-principle-of-permanent-confinement-pqnk-bed-geometry/",
  "https://pedaver.com/papers/national-food-power-and-agricultural-civilization/",
  "https://pedaver.com/papers/nutrition-dense-food-and-ecological-quality/",
  "https://pedaver.com/papers/farm-design-and-conversion-to-pqnk/",
  "https://pedaver.com/papers/the-role-of-jantar-in-biological-reconstruction/",
  "https://pedaver.com/papers/the-weed-indicator-system/",
  "https://pedaver.com/papers/pest-ecology-and-the-collapse-of-biological-balance/",
  "https://pedaver.com/papers/root-retention-science/",
  "https://pedaver.com/papers/every-seed-is-a-promise/",
  "https://pedaver.com/papers/why-conventional-rice-keeps-failing/",
  "https://pedaver.com/papers/technical-adaptations-for-mechanized-sri-production/",
  "https://pedaver.com/papers/the-missing-synthesis/",
  "https://pedaver.com/papers/what-science-delivered/",
  "https://pedaver.com/papers/why-leaves-change-color-with-the-weather/",
  "https://pedaver.com/papers/the-pqnk-framework-for-regenerative-animal-husbandry/",
  "https://pedaver.com/papers/the-origin-of-plant-mass-and-the-role-of-the-soil-system/",
  "https://pedaver.com/papers/pqnk-vs-soil-science-for-regenerative-agriculture/",
  "https://pedaver.com/papers/natures-algorithm-for-abundant-food/",
  "https://pedaver.com/papers/commercial-advantages-of-pqnk-production/",
  "https://pedaver.com/papers/wealth-generation-value-addition-and-money-circulation/",
  "https://pedaver.com/papers/how-pqnk-delivers-the-highest-nutrition-at-the-lowest-cost/",
  "https://pedaver.com/papers/the-looming-convergence-of-oil-and-food-crises/",
  "https://pedaver.com/papers/earth-to-food-reclaiming-our-agricultural-future/",
  "https://pedaver.com/papers/understanding-mulch-types-functions-and-selection/",
  "https://pedaver.com/papers/olive-under-pqnk/",
  "https://pedaver.com/papers/five-decades-of-agricultural-innovation/",
  "https://pedaver.com/papers/castor-cultivation-under-pqnk/",
  "https://pedaver.com/papers/citrus-kinnow-soil-strategy/",
  "https://pedaver.com/papers/mango-sop-under-pqnk/",
  "https://pedaver.com/papers/onion-seed-production-under-pqnk/",
  "https://pedaver.com/papers/pqnk-onion-garlic-production-system/",
  "https://pedaver.com/papers/a-farmers-guide-to-olive-orchards/",
  "https://pedaver.com/papers/potato-planting-depth-vs-mulch-no-till/",
  "https://pedaver.com/papers/achieving-high-yields-in-mature-pqnk-potato-systems/",
  "https://pedaver.com/papers/pqnk-and-plant-tropism/",
  "https://pedaver.com/papers/adapting-to-erratic-weather-using-pqnk-principles/",
  "https://pedaver.com/papers/pqnk-guide-to-wheat-cultivation/",
  "https://pedaver.com/papers/pqnk-wheat-growing-checklist/",
  "https://pedaver.com/papers/the-pqnk-strawberry-production-system/",
  "https://pedaver.com/papers/returning-dairy-waste-to-the-land/",
  "https://pedaver.com/papers/the-pqnk-kitchen-garden/",
  "https://pedaver.com/papers/answers-to-questions-on-soil-carbon/",
  "https://pedaver.com/papers/composition-of-black-soil/",
  "https://pedaver.com/papers/how-microbial-biodiversity-mines-geological-abundance/",
  "https://pedaver.com/papers/how-residue-management-affects-microbial-activity/",
  "https://pedaver.com/papers/soil-moisture-management-in-pqnk-organic-farming/",
  "https://pedaver.com/papers/the-living-soil-why-your-orchard-floor-matters/",
  "https://pedaver.com/papers/the-perenniality-of-the-soil-system/",
  "https://pedaver.com/papers/the-pest-free-revolution/",
  "https://pedaver.com/papers/understanding-soil-water-absorption/",
  "https://pedaver.com/papers/the-soil-biome-and-water-nutrient-dynamics-in-pqnk/",
  "https://pedaver.com/papers/two-pathways-to-pest-resistance/",
  "https://pedaver.com/papers/pqnk-advisory-frost-cold-weather-irrigation/",
  "https://pedaver.com/papers/cold-and-heat-induced-vascular-stress-in-plants/",
  "https://pedaver.com/papers/beyond-the-timeline-reframing-the-transition/",
  "https://pedaver.com/papers/deeper-understanding-of-pqnk-ecosystem-science/",
  "https://pedaver.com/papers/balangu-and-basil-seed-production-under-pqnk/",
  "https://pedaver.com/papers/watermelon-cultivation-pruning-and-nutrition-qa/",
  "https://pedaver.com/papers/narc-pnard-wheat-ras-field-trials/",
  "https://pedaver.com/papers/phosphate-from-sahara-desert-to-amazon/",
  "https://pedaver.com/papers/subsoiler-line-spacing-farmer-qa/",
  "https://pedaver.com/papers/cropland-as-a-carbon-sink-qa/",
  "https://pedaver.com/papers/beyond-the-nodule-soil-aeration-for-non-legumes/",
  "https://pedaver.com/papers/subsoil-compaction-no-till-vs-pqnk-critical-analysis/",
  "https://pedaver.com/papers/agriculture-in-sandy-soil-lecture-transcript/",
  "https://pedaver.com/papers/science-behind-the-myth-of-cow-dung-and-urine/",
  "https://pedaver.com/papers/flood-irrigation-and-jaggery-water-microbes-qa/",
  "https://pedaver.com/papers/when-a-natural-climate-cycle-meets-a-broken-planet/",
  "https://pedaver.com/papers/the-hidden-crisis-industrial-agriculture-and-the-water-cycle/",
  "https://pedaver.com/papers/the-greatest-climate-solution/",
  "https://pedaver.com/papers/field-diagnostic-guide-roots-sap-and-pests/",
  "https://pedaver.com/papers/open-field-vertical-farming-under-pqnk/",
  "https://pedaver.com/papers/seed-resistance-in-the-stomach-endozoochory/",
  "https://pedaver.com/papers/why-unscientific-organic-farming-can-be-dangerous/",
  "https://pedaver.com/papers/the-broken-chain-food-body-ecosystem-symbiosis/",
  "https://pedaver.com/papers/the-pqnk-food-chain-bio-potentiation/",
  "https://pedaver.com/papers/the-nutritional-roots-of-healthcare-expansion/",
  "https://pedaver.com/papers/pqnk-imperative-restoring-food-health-sovereignty/",
  "https://pedaver.com/papers/pqnk-response-to-national-agricultural-biotechnology-policy-2025/",
  "https://pedaver.com/papers/recalibrating-pakistans-textile-value-chain/",
  "https://pedaver.com/papers/the-ethics-of-the-closed-loop-system/",
  "https://pedaver.com/papers/failure-in-farm-management-inheritance-without-professionalization/",
  "https://pedaver.com/papers/white-and-green-growth-after-irrigation-qa/",
  "https://pedaver.com/papers/the-pqnk-system-of-assessment/",

  // One-time addition: legacy URL that now redirects, submitted so
  // participating engines re-crawl it and pick up the 301 -> /founder/
  // faster (not part of the "principal knowledge corpus" above).
  "https://pedaver.com/sample-page/",
];
